# -*- coding: utf-8 -*-
"""Plant Disease Detection using Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnR39z3PUBuJZRhvccjx1yIPUEFxh4Um
"""

import numpy as np
import pandas as pd
import os
import matplotlib as plt
import tensorflow as tf
from tensorflow.keras import layers

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/archive.zip"

import zipfile

zip_path = "/content/drive/MyDrive/archive.zip"
extract_path = "/content/kaggle_data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Done extracting")

import os
os.listdir("/content/kaggle_data")

train_dir = "/content/kaggle_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train"
valid_dir = "/content/kaggle_data/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid"

import tensorflow as tf

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=(224, 224),
    batch_size=32,
    label_mode="categorical",
    shuffle=True
)

valid_ds = tf.keras.utils.image_dataset_from_directory(
    valid_dir,
    image_size=(224, 224),
    batch_size=32,
    label_mode="categorical",
    shuffle=False
)

tf.random.set_seed(42)
model = tf.keras.Sequential([
    layers.Input(shape=(224, 224, 3)),

    layers.Conv2D(512, 3, activation="relu"),
    layers.MaxPooling2D(),

    layers.Conv2D(256, 3, activation="relu"),
    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, activation="relu"),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation="relu"),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(256, activation="relu"),
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(38, activation="softmax")

])

model.compile(loss="categorical_crossentropy", optimizer=tf.keras.optimizers.Nadam(learning_rate=0.0009), metrics=["accuracy"])

model.fit(train_ds, epochs = 10, validation_data = valid_ds)



